import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const base=process.env.DIARY_TEST_URL||'http://127.0.0.1:5178';
const results=[];
async function get(){const r=await fetch(base+'/api/diary');assert.equal(r.status,200);return r.json()}
async function post(p,expected=200){const r=await fetch(base+'/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));return d}
async function check(id,fn){try{await fn();results.push({id,status:'PASS'})}catch(e){results.push({id,status:'FAIL',error:e.message});throw e}}
let planId,taskIds=[];
try{
 await check('plan-fields-and-original-history',async()=>{const p=await post({action:'createPlan',title:'[검증 전용] 합성 계획',startDate:'2026-09-29',endDate:'2026-10-11',priority:1,successCriteria:'<script>window.__xss=1</script>',estimatedMinutes:240,estimatedKnown:1},201);planId=p.id;let d=await get(),v=d.plans.find(x=>x.id===planId);assert.equal(v.estimatedMinutes,240);await post({action:'updatePlan',id:planId,version:1,title:'[검증 전용] 합성 계획 수정',startDate:v.startDate,endDate:v.endDate,priority:2,successCriteria:v.successCriteria,estimatedMinutes:300,estimatedKnown:1});d=await get();const h=d.planVersions.filter(x=>x.planId===planId);assert.equal(h.length,2);assert.equal(JSON.parse(h[0].snapshot).estimatedMinutes,240);assert.equal(d.plans.find(x=>x.id===planId).id,planId)});
 await check('task-crud-and-fields',async()=>{for(let i=0;i<6;i++){const t=await post({action:'createTask',planId,title:'합성 작업 '+i,dueDate:i<3?'2026-09-30':'2026-10-11',priority:i%3+1,tags:'합성,검증',estimatedMinutes:30+i,estimatedKnown:1},201);taskIds.push(t.id)}const d=await get(),t=d.tasks.find(x=>x.id===taskIds[0]);await post({action:'updateTask',...t,title:'<img src=x onerror=window.__xss=1>'});const x=(await get()).tasks.find(x=>x.id===t.id);assert.equal(x.tags,'합성,검증');assert.equal(x.version,2)});
 await check('completion-double-submit-concurrent',async()=>{const t=(await get()).tasks.find(x=>x.id===taskIds[0]);await Promise.all([post({action:'completeTask',id:t.id,version:t.version,requestKey:crypto.randomUUID()}),post({action:'completeTask',id:t.id,version:t.version,requestKey:crypto.randomUUID()})]);const d=await get();assert.equal(d.completions.filter(x=>x.taskId===t.id).length,1);assert.equal(d.tasks.filter(x=>x.planId===planId&&x.status==='done').length,1)});
 await check('reopen-and-old-request-replay',async()=>{let d=await get(),t=d.tasks.find(x=>x.id===taskIds[0]),old=d.completions.find(x=>x.taskId===t.id);await post({action:'reopenTask',id:t.id,version:t.version});await post({action:'completeTask',id:t.id,version:t.version,requestKey:old.requestKey});d=await get();assert.equal(d.tasks.find(x=>x.id===t.id).status,'todo');const fresh=d.tasks.find(x=>x.id===t.id);await post({action:'completeTask',id:fresh.id,version:fresh.version,requestKey:crypto.randomUUID()});assert.equal((await get()).completions.filter(x=>x.taskId===t.id).length,2)});
 await check('execution-time-blocker-and-plan-preservation',async()=>{const before=(await get()).plans.find(x=>x.id===planId);for(let i=0;i<3;i++){const key=crypto.randomUUID(),p={action:'createExecution',taskId:taskIds[i],startAt:'2026-10-01T10:00:00+09:00',endAt:`2026-10-01T10:${30+i}:00+09:00`,blockedReason:i<2?'통로 충돌':'',requestKey:key};await post(p,201);await post(p)}const d=await get();assert.deepEqual(d.plans.find(x=>x.id===planId),before);assert.equal(d.executions.filter(x=>taskIds.includes(x.taskId)).length,3);assert.equal(d.executions.find(x=>x.taskId===taskIds[0]).actualMinutes,30)});
 await check('delete-excludes-with-history-retained',async()=>{await post({action:'deleteTask',id:taskIds[5]});const d=await get();assert.ok(d.tasks.find(x=>x.id===taskIds[5]).deletedAt);assert.equal(d.tasks.filter(x=>x.planId===planId&&!x.deletedAt).length,5)});
 await check('review-to-next-plan',async()=>{const r=await post({action:'createReview',planId,startDate:'2026-09-29',endDate:'2026-10-11',improvement:'합성 개선점: 동선 먼저 검사'},201);const n=await post({action:'createPlan',title:'[검증 전용] 다음 계획',startDate:'2026-10-12',endDate:'2026-10-13',priority:2,successCriteria:'합성',estimatedMinutes:0,estimatedKnown:0,sourceReviewId:r.id},201);const p=(await get()).plans.find(x=>x.id===n.id);assert.equal(p.sourceReviewId,r.id);assert.equal(p.improvement,'합성 개선점: 동선 먼저 검사');assert.equal(p.estimatedKnown,0)});
 await check('invalid-input-keeps-data-and-version-conflicts',async()=>{const before=await get();await post({action:'createExecution',taskId:taskIds[0],startAt:'2026-10-01T12:00:00+09:00',endAt:'2026-10-01T11:00:00+09:00',blockedReason:'',requestKey:crypto.randomUUID()},400);await post({action:'updatePlan',id:planId,version:1,title:'불가',startDate:'2026-10-01',endDate:'2026-10-11',priority:2,successCriteria:'불가',estimatedMinutes:0,estimatedKnown:1},409);const after=await get();assert.deepEqual(after.plans,before.plans);assert.deepEqual(after.executions,before.executions)});
 await check('reload-full-record-identity',async()=>{assert.deepEqual(await get(),await get())});
}finally{await writeFile('tests/api-results.json',JSON.stringify({synthetic:true,base,at:new Date().toISOString(),results,planId,taskIds},null,2));console.log(JSON.stringify(results));}
