"use client";
import {useEffect,useState} from 'react';
import {Castle,Download,Plus,BookOpen,Clock3,ListChecks} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {type Data,type Plan,type Task,summarize,seoulDate} from '@/lib/domain';
const empty:Data={plans:[],tasks:[],executions:[],reviews:[],planVersions:[],completions:[],today:seoulDate()};
function Choice({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Field({label,name,value='',type='text',required=true}:{label:string;name:string;value?:string|number;type?:string;required?:boolean}){return <label className="field">{label}<input name={name} type={type} defaultValue={value} required={required} min={type==='number'?0:undefined} step={type==='number'?1:undefined}/></label>}
export default function Diary(){
 const [data,setData]=useState<Data>(empty),[selected,setSelected]=useState(''),[tab,setTab]=useState('plan'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [modal,setModal]=useState<'plan'|'task'|'execution'|null>(null),[edit,setEdit]=useState<Plan|Task|null>(null),[priority,setPriority]=useState('2'),[status,setStatus]=useState('all'),[sort,setSort]=useState('due'),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[activeTask,setActiveTask]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[proof,setProof]=useState(''),[pendingReview,setPendingReview]=useState<any>(null),[requestKey,setRequestKey]=useState('');
 async function load(){try{const r=await fetch('/api/diary',{cache:'no-store'});if(!r.ok)throw Error('자료를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.');const d=await r.json() as Data;setData(d);setSelected(s=>s||d.plans[0]?.id||'');setError('');}catch(e:any){setError(e.message);}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function mutate(action:string,payload:any){setBusy(true);setError('');try{const r=await fetch('/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d:any=await r.json();if(!r.ok)throw Error(d.error||'저장하지 못했습니다.');await load();toast.success('저장했습니다');return d;}catch(e:any){setError(e.message);toast.error(e.message);throw e;}finally{setBusy(false)}}
 function open(kind:typeof modal,item:Plan|Task|null=null){setEdit(item);setPriority(String(item?.priority||2));setRequestKey(crypto.randomUUID());setModal(kind)}
 const plan=data.plans.find(p=>p.id===selected),tasks=data.tasks.filter(t=>t.planId===selected&&!t.deletedAt),summary=summarize(data,selected,from,to);
 const visible=tasks.filter(t=>(status==='all'||t.status===status)&&(t.title+' '+t.tags).toLowerCase().includes(query.toLowerCase())&&(!tag||t.tags.split(',').map(x=>x.trim()).includes(tag))).sort((a,b)=>(sort==='priority'?a.priority-b.priority:sort==='estimate'?a.estimatedMinutes-b.estimatedMinutes:a.dueDate.localeCompare(b.dueDate))||a.id.localeCompare(b.id));
 async function saveForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=Object.fromEntries(f);try{let result:any;if(modal==='plan'){result=await mutate(edit?'updatePlan':'createPlan',{...p,priority:Number(priority),estimatedMinutes:Number(p.estimatedMinutes),estimatedKnown:p.estimatedMinutes!=='' ? 1 : 0,id:edit?.id,version:edit?.version,sourceReviewId:pendingReview?.id||null,improvement:pendingReview?.improvement||''});if(!edit)setSelected(result.id);setPendingReview(null);}else if(modal==='task'){await mutate(edit?'updateTask':'createTask',{...p,priority:Number(priority),estimatedMinutes:Number(p.estimatedMinutes),estimatedKnown:p.estimatedMinutes!=='' ? 1 : 0,planId:selected,id:edit?.id,version:edit?.version});}else{await mutate('createExecution',{...p,taskId:activeTask,startAt:String(p.startAt)+':00+09:00',endAt:String(p.endAt)+':00+09:00',requestKey});}setModal(null);}catch{}}
 function exportAll(){const blob=new Blob([JSON.stringify({schemaVersion:2,timeZone:'Asia/Seoul',unit:'minutes',exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='manor-diary.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'read_manor_diary',description:'현재 제작 일지의 저장된 계획, 할 일, 실행 기록을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw Error('입력 항목이 없습니다.');const r=await fetch('/api/diary');if(!r.ok)throw Error('조회 실패');return r.json()}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 return <div className="diary"><Toaster/><aside className="rail"><div className="brand"><Castle size={25}/><span>ESCAPE MAP<br/><small>PRODUCTION JOURNAL</small></span></div><p className="rail-label">제작 노트</p>{[['plan','계획과 할 일',BookOpen],['do','실제 작업',Clock3],['see','돌아보기',ListChecks]].map(([key,label,Icon]:any)=><button key={key} className={tab===key?'nav active':'nav'} onClick={()=>setTab(key)}><Icon size={18}/>{label}</button>)}<div className="rail-bottom">고고학자의 대저택<br/><span>조금씩, 완성에 가까이.</span></div></aside>
 <main className="workspace"><header><div><p className="eyebrow">PLAN / DO / SEE</p><h1>탈출게임 맵 제작 일지</h1></div><button className="secondary" onClick={exportAll} disabled={loading||!!error}><Download size={17}/>자료 내보내기</button></header>
 {error&&<div role="alert" className="error">{error}<button onClick={load}>다시 불러오기</button></div>}
 <div className="plan-picker"><Choice label="계획 선택" value={selected||'none'} options={data.plans.length?data.plans.map(p=>[p.id,p.title]):[['none','아직 저장된 계획이 없습니다']]} onChange={setSelected}/><button className="primary" onClick={()=>{setPendingReview(null);open('plan')}}><Plus size={17}/>새 계획</button><span className="meta">서울 기준 {data.today} · 시간 단위: 분</span></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="journal-tabs"><TabsTrigger value="plan">01 계획</TabsTrigger><TabsTrigger value="do">02 실제 작업</TabsTrigger><TabsTrigger value="see">03 돌아보기</TabsTrigger></TabsList>
 <TabsContent value="plan"><section className="panel"><div className="section-head"><div><p className="eyebrow">PLAN</p><h2>{plan?.title||'첫 제작 계획을 세워 보세요'}</h2></div>{plan&&<button className="secondary" onClick={()=>open('plan',plan)}>계획 수정</button>}</div>{plan?<><div className="plan-facts"><div><span>기간</span><strong>{plan.startDate} ~ {plan.endDate}</strong></div><div><span>우선순위</span><strong>{['','높음','보통','낮음'][plan.priority]}</strong></div><div><span>예상 시간</span><strong>{plan.estimatedKnown?`${plan.estimatedMinutes}분`:'미정'}</strong></div></div><p className="criterion"><span>성공 기준</span>{plan.successCriteria}</p>{plan.improvement&&<p className="criterion"><span>지난 돌아보기에서</span>{plan.improvement}</p>}<details><summary>수정 이력 · 이전 계획 보기</summary>{data.planVersions.filter(v=>v.planId===selected).map(v=><div className="history" key={v.id}><strong>버전 {v.version}</strong><pre>{JSON.stringify(JSON.parse(v.snapshot),null,2)}</pre></div>)}</details></>:<p className="empty">작업 목표, 기간, 성공 기준과 예상 시간을 함께 남깁니다.</p>}</section>
 <section className="panel"><div className="section-head"><div><h2>할 일</h2><p className="meta">공간을 만들고, 직접 걸어 보고, 개선하기.</p></div><button className="primary" disabled={!plan} onClick={()=>open('task')}><Plus size={17}/>할 일 추가</button></div><div className="filters"><input aria-label="할 일 검색" placeholder="제목 또는 태그 검색" value={query} onChange={e=>setQuery(e.target.value)}/><Choice label="상태 필터" value={status} onChange={setStatus} options={ [['all','모든 상태'],['todo','진행 중'],['done','완료']]}/><Choice label="정렬" value={sort} onChange={setSort} options={ [['due','마감일 빠른순'],['priority','우선순위 높은순'],['estimate','예상 시간 짧은순']]}/><input aria-label="태그 필터" placeholder="태그로 거르기" value={tag} onChange={e=>setTag(e.target.value)}/></div><p className="meta">정렬: {sort==='due'?'마감일 오름차순':sort==='priority'?'우선순위 높음 → 낮음':'예상 시간 오름차순'} · 값이 같으면 ID 오름차순</p><div className="task-list">{visible.map(t=><article className="task" key={t.id}><button className={'status-button '+(t.status==='done'?'done':'')} aria-label={t.title+(t.status==='done'?' 완료 되돌리기':' 완료 처리')} disabled={busy} onClick={()=>mutate(t.status==='done'?'reopenTask':'completeTask',{id:t.id,requestKey:crypto.randomUUID(),version:t.version}).catch(()=>{})}>{t.status==='done'?'✓':''}</button><div className="task-text"><h3>{t.title}</h3><p>{t.dueDate} · {['','높음','보통','낮음'][t.priority]} · 예상 {t.estimatedKnown?`${t.estimatedMinutes}분`:'미정'}</p><span>{t.tags||'태그 없음'}</span></div><span className={'pill '+(t.status==='done'?'complete':'')}>{t.status==='done'?'완료':'진행 중'}</span><button className="text-button" onClick={()=>open('task',t)}>수정</button><button className="text-button danger" onClick={()=>{setActiveTask(t.id);setProof('delete')}}>삭제</button></article>)}</div>{!visible.length&&<p className="empty">{loading?'저장된 자료를 불러오는 중입니다.':tasks.length?'조건에 맞는 할 일이 없습니다.':'새 계획을 고른 뒤, 실제 할 일을 추가해 주세요.'}</p>}</section></TabsContent>
 <TabsContent value="do"><section className="panel"><div className="section-head"><div><p className="eyebrow">DO</p><h2>실제 작업 기록</h2><p className="meta">계획은 그대로 두고, 실제로 한 일을 따로 남깁니다.</p></div><button className="primary" disabled={!tasks.length} onClick={()=>{setActiveTask(tasks[0]?.id||'');open('execution')}}><Plus size={17}/>작업 기록 추가</button></div>{data.executions.filter(e=>tasks.some(t=>t.id===e.taskId)).map(e=><article className="execution" key={e.id}><h3>{tasks.find(t=>t.id===e.taskId)?.title}</h3><p>{new Date(e.startAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} ~ {new Date(e.endAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><strong>{e.actualMinutes}분</strong><p className="block-reason">막힌 이유: {e.blockedReason||'없음'}</p><small>ID {e.id}</small></article>)}{!data.executions.some(e=>tasks.some(t=>t.id===e.taskId))&&<p className="empty">실제로 작업한 시작·종료 시각과 막힌 이유를 기록해 주세요.</p>}</section></TabsContent>
 <TabsContent value="see"><section className="panel"><div className="section-head"><div><p className="eyebrow">SEE</p><h2>계획과 실제 사이</h2><p className="meta">선택한 계획의 할 일 마감일 기준으로 기간을 거릅니다. 숫자를 누르면 근거 기록이 열립니다.</p></div></div><div className="filters"><label className="field">시작 마감일<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">종료 마감일<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom('');setTo('')}}>전체 기간</button></div>{from&&to&&from>to?<p role="alert" className="error">종료일은 시작일 이후여야 합니다.</p>:<><div className="stats">{[['planned','계획한 일'],['completed','완료한 일'],['delayed','지연된 일'],['blocked','막힌 일']].map(([key,label])=><button key={key} className="stat" onClick={()=>setProof(key)}><span>{label}</span><strong>{(summary as any)[key].length}<small>건</small></strong></button>)}</div>{summary.unknownEstimates>0&&<p className="meta">예상 시간 미정 {summary.unknownEstimates}건은 합계에서 제외합니다. 차이도 입력된 예상 시간만 기준으로 계산합니다.</p>}<div className="time-compare"><button onClick={()=>setProof('estimated')}><span>예상 시간</span><strong>{summary.estimated}분</strong></button><button onClick={()=>setProof('actual')}><span>실제 시간</span><strong>{summary.actual}분</strong></button><button onClick={()=>setProof('difference')}><span>실제 − 예상</span><strong>{summary.difference>0?'+':''}{summary.difference}분</strong></button></div></>}
 <form className="review-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await mutate('createReview',{planId:selected,startDate:from||plan?.startDate,endDate:to||plan?.endDate,improvement:f.get('improvement')});form.reset()}catch{}}}><h3>다음 제작에서 바꿀 한 가지</h3><textarea aria-label="다음 계획 개선점" name="improvement" required placeholder="예: 가구를 배치하기 전에 통로 폭부터 확인하기"/><button className="primary" disabled={busy||!plan||!!(from&&to&&from>to)}>돌아보기 저장</button></form>{data.reviews.filter(r=>r.planId===selected).map(r=><article className="review" key={r.id}><p>{r.improvement}</p><button className="secondary" onClick={()=>{setPendingReview(r);open('plan')}}>이 개선점으로 다음 계획 만들기</button></article>)}</section></TabsContent></Tabs><footer>기록은 서버에 저장됩니다. 계획 수정 이력과 삭제한 할 일도 전체 내보내기에 포함됩니다.</footer></main>
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="journal-dialog"><DialogTitle>{modal==='plan'?(edit?'계획 수정':'새 제작 계획'):modal==='task'?(edit?'할 일 수정':'할 일 추가'):'실제 작업 기록'}</DialogTitle><DialogDescription>{modal==='execution'?'시각은 서울 시간으로 입력합니다. 실제 시간은 시작과 종료 차이에서 계산됩니다.':'공개해도 괜찮은 내용만 입력해 주세요.'}</DialogDescription><form onSubmit={saveForm} key={modal+'-'+edit?.id}>
 {modal==='execution'?<><label className="field">연결할 할 일<Choice label="기록의 할 일" value={activeTask} onChange={setActiveTask} options={tasks.map(t=>[t.id,t.title])}/></label><Field label="시작 시각 (서울)" name="startAt" type="datetime-local"/><Field label="종료 시각 (서울)" name="endAt" type="datetime-local"/><label className="field">막힌 이유 (없으면 비워 두기)<textarea name="blockedReason"/></label></>:<><Field label={modal==='plan'?'계획 제목':'할 일 제목'} name="title" value={edit?.title}/><div className="form-grid">{modal==='plan'?<><Field label="시작일" name="startDate" type="date" value={(edit as Plan)?.startDate||data.today}/><Field label="종료일" name="endDate" type="date" value={(edit as Plan)?.endDate||data.today}/></>:<Field label="마감일" name="dueDate" type="date" value={(edit as Task)?.dueDate||data.today}/>}<Field label="예상 시간 (분, 미정이면 비워 두기)" name="estimatedMinutes" type="number" value={edit?.estimatedKnown?edit.estimatedMinutes:''} required={false}/><label className="field">우선순위<Choice label="우선순위" value={priority} onChange={setPriority} options={ [['1','높음'],['2','보통'],['3','낮음']]}/></label></div>{modal==='plan'?<label className="field">성공 기준<textarea name="successCriteria" defaultValue={(edit as Plan)?.successCriteria} required/></label>:<Field label="태그 (쉼표로 구분)" name="tags" value={(edit as Task)?.tags} required={false}/>} {pendingReview&&<p className="criterion">이어 받은 개선점: {pendingReview.improvement}</p>}</>}
 {error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'저장 중…':'저장'}</button></form></DialogContent></Dialog>
 <Dialog open={!!proof&&proof!=='delete'} onOpenChange={o=>!o&&setProof('')}><DialogContent className="journal-dialog"><DialogTitle>집계 근거 기록</DialogTitle><DialogDescription>선택한 기간에 속하는 할 일과 그 실행 기록입니다. 단위: 분</DialogDescription>{(proof==='actual'?summary.executions:['estimated','difference'].includes(proof)?summary.planned:(summary as any)[proof]||[]).map((x:any)=><article className="execution" key={x.id}><strong>{x.title||tasks.find(t=>t.id===x.taskId)?.title}</strong><p>ID {x.id}</p>{x.actualMinutes!==undefined?<p>실제 {x.actualMinutes}분 · {x.blockedReason||'막힘 없음'}</p>:<p>마감 {x.dueDate} · {x.status==='done'?'완료':'진행 중'} · 예상 {x.estimatedMinutes}분{proof==='difference'&&` · 실제 ${summary.executions.filter(e=>e.taskId===x.id).reduce((n,e)=>n+e.actualMinutes,0)}분`}</p>}</article>)}{!(proof==='actual'?summary.executions:['estimated','difference'].includes(proof)?summary.planned:(summary as any)[proof]||[]).length&&<p>해당 기록이 없습니다.</p>}</DialogContent></Dialog>
 <AlertDialog open={proof==='delete'} onOpenChange={o=>!o&&setProof('')}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>이 할 일을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>목록과 집계에서 제외합니다. 실행 기록과 삭제 이력은 전체 내보내기에 보관됩니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();mutate('deleteTask',{id:activeTask}).then(()=>setProof('')).catch(()=>{})}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
